name = "spinmachoapp-es"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinmachoapp.es"
HMAC_KEY = "d54113764efda67d176919aec2bd4c20fddeb5608de8da61e48c4644b2bd02ca"
COOKIE_NAME = "6t0"
PLAY_PATH = "start"
BUTTON_ID = "pd4b39b1d1947c190fa944066f5932796"
GATE_SALT = "d56d46d176f12ec9"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "vp9f"
CTA_SELECTOR = ".play-button"
